### ISSUE TITLE
Add support to expand URLs

### ISSUE THREAD

**Issue by brennanMKE** [brennanMKE/BitlyForiOS#3]

**Comment by claesjacobsson** [comment]
+1

**Comment by brennanMKE** [comment]
Sorry, this feature has been in the code but this issue was still open. I also just updated it to eliminate AFNetworking as a dependency. This will likely be the last update as the next version will be Swift. This update does include automated tests to confirm functionality which will help ensure it is working going forward.

cc @claesjacobsson

**Comment by claesjacobsson** [comment]
Great, thanks.
