### ISSUE TITLE
Update to OAuth service?

### ISSUE THREAD

**Issue by claesjacobsson** [brennanMKE/BitlyForiOS#5]
Any thoughts on the update to the OAuth service? Current version works fine, but how long will Bitly support it? 

Emailed Bitly about it today. Will post the answer here.

**Comment by claesjacobsson** [comment]
Response from Bitly: 

"We do not have plans to remove API key support from those API end points that support it, but as we create new endpoints, we're not building them with API key support. So older libraries such as the one you are using won't have access to our newer functionality."

**Comment by brennanMKE** [comment]
This code supports OAuth. You just need to provide your access token.
